/* ==========================================================
   TC ROBOTICS - 사이트 기본 데이터

   글 수정 권장:
   - 한국어: HANYO_TEXT.txt
   - English: HANYO_TEXT_EN.txt
   - 일본어/러시아어/힌디어/불가리아어: EDIT_HERE.html 또는 이 파일

   한국어/영어 TXT를 불러올 수 없는 환경에서는 아래 값이 예비 문구로 사용됩니다.
   ========================================================== */

const SITE_CONFIG = {
  "logo": "assets/images/tc-logo.png",
  "applyUrl": "#",
  "media": {
    "heroImage": "",
    "heroVideo": "",
    "aboutImage": "",
    "activityImage": "",
    "gallery1": "",
    "gallery2": "",
    "gallery3": "",
    "gallery4": "",
    "gallery5": "",
    "mediaVideo": ""
  }
};

const SITE_TEXT = {
  "ko": {
    "topline": "FTC · ROBOT BUILD · PROGRAMMING",
    "clubName": "TC Robotics Club",
    "schoolName": "운천고등학교",
    "navHome": "홈",
    "navAbout": "동아리 소개",
    "navActivity": "활동 · 대회",
    "navMedia": "사진 · 영상",
    "navJoin": "지원 안내",
    "heroKicker": "운천고등학교 로보틱스 동아리",
    "heroTitle": "Think<br>Create<br><strong style=\"font-weight:900;color:var(--accent)\">We are TC.</strong>",
    "heroLead": "저희는 운천고등학교를 대표하는 Think &amp; Creative(TC) 동아리로, <br>‘틀을 깨고 다양한 생각을 하자’는 의미처럼 창의성과 도전 정신을 기릅니다.",
    "heroAbout": "동아리 알아보기",
    "heroJoin": "지원 안내",
    "mini1Title": "ROBOT BUILD",
    "mini1Text": "설계 · 조립 · 개선",
    "mini2Title": "PROGRAMMING",
    "mini2Text": "센서 · 모터 · 자율주행",
    "mini3Title": "COMPETITION",
    "mini3Text": "전략 · 테스트 · 경기",
    "mediaHeroLabel": "대표 사진 또는 경기 영상",
    "seasonLabel": "THIS SEASON",
    "seasonTitle": "FIRST CANOPY",
    "seasonText": "&lt;2026년 9월 12일 공개!&gt;<br>자연과 생물 다양성",
    "strip1Label": "CLUB",
    "strip2Label": "SCHOOL",
    "strip3Label": "TEAM",
    "strip4Label": "FOCUS",
    "strip4Value": "ROBOTICS · FTC",
    "homeKicker": "TC 한눈에 보기",
    "homeTitle": "관심 있는 내용부터 확인해보세요.",
    "homeCopy": "TC의 특색을 여러 갈래로 갈랐습니다. 그외의 궁금한 점은 문의 부탁드립니다.",
    "homeCard1Title": "어떤 동아리인가요?",
    "homeCard1Text": "TC는 하나의 동아리로 학생들이 주도적으로 어떻게 활동하는지 서술합니다.",
    "homeCard2Title": "로봇은 어떻게 완성되나요?",
    "homeCard2Text": "한 시즌을 위해 어떻게 로봇을 만들어가는지 실시간으로 공유됩니다.",
    "homeCard3Title": "그외의 활동은 무엇이 있나요?",
    "homeCard3Text": "TC의 성장 과정을 공유합니다.",
    "more": "자세히 보기 →",
    "aboutKicker": "동아리 소개",
    "aboutTitle": "TC는 2012년부터 이어온 전통과 노하우를 가지고 있습니다.",
    "aboutLead": "TC는 단지 고등학교의 동아리로 끝나는 것이 아닌, 미래 융합전형인재를 길러내기 위해 오너십을 가진 학생들로팀을 꾸려 함께 나아갑니다.<br>오랜 운영 실력으로 대회에서 1등을 차지하는 만큼 뛰어난 영량을 갖추고 있습니다.<br>KLA 장학팀에 다년간 연속 선정되며 학업과 탐구 영역을 넓히고 있습니다.",
    "aboutCard1Title": "기계 설계 · 제작",
    "aboutCard1Text": "매 시즌마다 규정에 맞게 프레임을 조정하고 어떤 것이 더 효율적인지를 판단하며 제작합니다.",
    "aboutCard2Title": "로봇 프로그래밍",
    "aboutCard2Text": "모터와 센서를 제어하고 자율주행 및 드라이버 제어 코드를 작성합니다.",
    "aboutCard3Title": "반복 테스트",
    "aboutCard3Text": "실제 경기 상황을 가정해 문제를 찾고, 구조와 코드를 계속 개선합니다.",
    "aboutCard4Title": "팀으로 해결하기",
    "aboutCard4Text": "기계, 코딩, 전략 역할이 서로 연결되어 한 대의 로봇을 완성합니다.",
    "aboutFeatureKicker": "신입 부원에게",
    "aboutFeatureTitle": "잘하는 학생보다,<br>직접 해보고 싶은 학생.",
    "aboutFeatureText": "로봇이나 코딩을 처음 접해도 괜찮습니다. 만들고 고치고 다시 시도하는 과정에 관심이 있다면 동아리 활동을 통해 배울 수 있습니다.",
    "joinButton": "지원 안내 보기",
    "activityKicker": "활동 · 대회",
    "activityTitle": "만들고, 코딩하고,<br>경기에서 검증합니다.",
    "activityLead": "실제 참가 대회와 시즌 일정이 정해지면 이 페이지의 텍스트만 바꿔도 됩니다. 아래 구조는 FTC와 같은 로봇 대회를 준비하는 일반적인 활동 흐름을 보여줍니다.",
    "step1Title": "게임 분석",
    "step1Text": "규칙과 과제를 확인하고 필요한 기능과 경기 전략을 정합니다.",
    "step2Title": "설계",
    "step2Text": "아이디어를 비교하고 로봇 구조와 메커니즘을 계획합니다.",
    "step3Title": "제작",
    "step3Text": "프레임과 부품을 조립해 실제 로봇 형태를 완성합니다.",
    "step4Title": "프로그래밍",
    "step4Text": "센서, 모터, 자율주행, 조종 코드를 구현합니다.",
    "step5Title": "테스트 · 대회",
    "step5Text": "반복 테스트와 개선을 거쳐 실제 경기에서 로봇을 운영합니다.",
    "competitionKicker": "대회 기록",
    "competitionTitle": "수상 이력",
    "competitionText": "2015-2016년 코리아로봇챔피언십 FTC 부문 Best Challenge award 수상<br>2016-2017 코리아로봇챔피언십 FTC 부문 Design award 수상, 어시스트 2위<br>2017-2018 코리아로봇챔피언십 FTC 부문 Think award 수상<br>2018-2019 코리아로봇챔피언십 FTC 부문 Inspire award 수상(종합1위), Judge award 수상<br>2020-2021 코라이로봇챔피언십 FTC 부문 Robot Game Winning 3rd Award(경기3위)<br>2021-2022 코리아로봇챔피언십 FTC 부문 Inspire award 2위(종합2위), Winning Alliance 1위 수상<br>2022-2023 코리아로봇챔피언십 FTC 부문 Creative Award, Judge Award 수상<br>2023 오산시 제1회 해커톤 대상 (2023.7.21. / 오산)<br>2023 KLA 장학 프로그램 Advance Insights Challenge 최우수상 (2023.11.20. / 수원)<br>2023-2024 코리아로봇챔피언십 FTC 부분 Winning Alliance-Captain(경기1위) 23020, Think Award 24906, Winning Alliance - 1st Team Selected 24906 (2024.1.27. / 대전)<br>2023-2024 FIRST World Championship(세계대회) 한국대표 출전 Judges’ Choice Award 수상 23020 (2024.4.20. / USA Houston)<br>2024 오산시 제2회 해커톤 장려상 (2024.8.23. / 오산)<br>2024 KLA 장학 프로그램 Advance Insights Challenge 경기 3위 (2024.11.16. / 수원)<br>2024-2025 코리아로봇챔피언십 FTC 부분 Inspire award 1st Place 수상(종합1위) 23020, Inspire award 2nd Place 수상(종합2위) 24906, Winning Alliance-1st Team Selected 24906, King Sejong Division Winning Alliance-1st Team Selected 24906 (2025.1.20. / 대전)<br>2024-2025 FIRST World Championship(세계대회) 한국대표 출전  (2025.4.16.-2025.4.19. / USA Houston)<br>2025 KLA 장학 프로그램 Design award 수상(24906) Engineering Notes 수상 (24906)<br>2025-2026 코리아로봇챔피언십 FTC 부문 Inspire award 3위(종합3위)수상 24906<br>Championship Finalist Alliance Award 수상 (24906)<br>2025-2026 FIRST World Championship(세계대회) 한국대표 출전(USA Houston)<br>2026 Mission Master 1nd Award, Mission Master 2nd Award (울산)",
    "mediaButton": "사진 · 영상 보기",
    "mediaKicker": "사진 · 영상",
    "mediaTitle": "실제 활동 기록을<br>한곳에서 보여주세요.",
    "mediaLead": "로봇 사진, 제작 과정, 경기 영상, 코드 화면을 나중에 넣을 수 있도록 미디어 영역을 별도 페이지로 구성했습니다.",
    "tabPhotos": "사진",
    "tabVideos": "영상",
    "tabCode": "코딩",
    "videoKicker": "영상 영역",
    "videoTitle": "경기 영상 또는<br>제작 타임랩스",
    "videoText": "실제 MP4 파일을 넣으면 이 공간에서 바로 재생할 수 있습니다. 제목과 설명도 나중에 수정 가능합니다.",
    "codeKicker": "로봇 코드",
    "codeTitle": "우리 로봇의 움직임을<br>만드는 코드.",
    "codeText": "자율주행, 센서 제어, 드라이버 제어 등 실제 팀 코드 중 짧은 예시를 넣으면 학생들이 활동 내용을 쉽게 이해할 수 있습니다.",
    "joinKicker": "지원 안내",
    "joinTitle": "다음 로봇을 함께 만들<br>팀원을 기다립니다.",
    "joinLead": "모집 일정과 지원 방법이 정해지면 아래 항목만 실제 정보로 교체하면 됩니다. QR 코드는 이 홈페이지 안에 넣지 않고 포스터나 인쇄물에서 별도로 사용할 수 있습니다.",
    "recruiting": "RECRUITING",
    "joinHeadline": "로봇을 좋아하거나,<br>직접 만들어보고 싶다면.",
    "joinText": "기계, 코딩, 경기 전략 중 어느 한 분야에 관심이 있어도 좋습니다. 실제 모집 기준에 맞춰 이 문구를 수정해 주세요.",
    "apply": "지원 링크 연결하기 →",
    "recruitInfo": "모집 정보",
    "targetLabel": "모집 대상",
    "targetValue": "운천고 1·2학년",
    "dateLabel": "모집 기간",
    "dateValue": "현재는 모집을 진행하고 있지 않습니다.",
    "placeLabel": "운천고등학교",
    "placeValue": "[활동 장]",
    "contactLabel": "문의",
    "contactValue": "[담당자 / 연락 방법]",
    "joinNotice": "현재는 모집을 진행하고 있지 않습니다.",
    "footerText": "© 2026 운천고등학교"
  },
  "en": {
    "topline": "FTC · ROBOT BUILD · PROGRAMMING",
    "clubName": "TC Robotics Club",
    "schoolName": "Uncheon High School",
    "navHome": "Home",
    "navAbout": "About the Club",
    "navActivity": "Activities · Competitions",
    "navMedia": "Photos · Videos",
    "navJoin": "Join Us",
    "heroKicker": "Uncheon High School Robotics Club",
    "heroTitle": "Think<br>Create<br><strong style=\"font-weight:900;color:var(--accent)\">We are TC.</strong>",
    "heroLead": "We are Think &amp; Creative (TC), a club representing Uncheon High School. True to our name—thinking beyond the usual frame and exploring different ideas—we grow through creativity, challenge, and hands-on problem solving.",
    "heroAbout": "Learn About TC",
    "heroJoin": "Join Us",
    "mini1Title": "ROBOT BUILD",
    "mini1Text": "Design · Build · Improve",
    "mini2Title": "PROGRAMMING",
    "mini2Text": "Sensors · Motors · Autonomous",
    "mini3Title": "COMPETITION",
    "mini3Text": "Strategy · Testing · Matches",
    "mediaHeroLabel": "Featured Photo or Match Video",
    "seasonLabel": "THIS SEASON",
    "seasonTitle": "FIRST CANOPY",
    "seasonText": "&lt;Coming September 12, 2026&gt;<br>Nature &amp; Biodiversity",
    "strip1Label": "CLUB",
    "strip2Label": "SCHOOL",
    "strip3Label": "TEAM",
    "strip4Label": "FOCUS",
    "strip4Value": "ROBOTICS · FTC",
    "homeKicker": "TC AT A GLANCE",
    "homeTitle": "Start with what interests you.",
    "homeCopy": "We have organized TC’s key features into several sections. If you have any other questions, please contact us.",
    "homeCard1Title": "What kind of club is TC?",
    "homeCard1Text": "See how students take the lead and work together as one team in TC.",
    "homeCard2Title": "How does a robot come together?",
    "homeCard2Text": "Follow how we build a competition robot throughout an entire season.",
    "homeCard3Title": "What else does TC do?",
    "homeCard3Text": "Explore the activities and milestones that show how TC continues to grow.",
    "more": "View Details →",
    "aboutKicker": "ABOUT THE CLUB",
    "aboutTitle": "TC has built its tradition and know-how since 2012.",
    "aboutLead": "TC aims to be more than just a high school club. Students take ownership of their roles, work as a team, and grow into future interdisciplinary problem-solvers. Years of experience have led to strong competition results, including first-place finishes. TC has also been selected for the KLA scholarship program for multiple consecutive years, expanding both academic and research opportunities.",
    "aboutCard1Title": "Mechanical Design · Build",
    "aboutCard1Text": "Each season, we adjust the frame to meet the rules, compare possible approaches, and build the robot based on what works most efficiently.",
    "aboutCard2Title": "Robot Programming",
    "aboutCard2Text": "We control motors and sensors and write autonomous and driver-control code.",
    "aboutCard3Title": "Repeated Testing",
    "aboutCard3Text": "We recreate real match situations, find problems, and continuously improve both the robot structure and the code.",
    "aboutCard4Title": "Solve It as a Team",
    "aboutCard4Text": "Mechanical, programming, and strategy roles connect with one another to complete a single robot.",
    "aboutFeatureKicker": "FOR NEW MEMBERS",
    "aboutFeatureTitle": "Not the student who already knows everything,<br>but the student who wants to try.",
    "aboutFeatureText": "It is okay if robotics or coding is completely new to you. If you are interested in building, fixing, and trying again, you can learn through TC activities.",
    "joinButton": "See How to Join",
    "activityKicker": "ACTIVITIES · COMPETITIONS",
    "activityTitle": "Build it. Code it.<br>Prove it in competition.",
    "activityLead": "When an actual competition and season schedule are confirmed, this page can be updated simply by changing the text. The flow below shows the typical process TC follows while preparing for robotics competitions such as FTC.",
    "step1Title": "Game Analysis",
    "step1Text": "Review the rules and challenges, then decide which robot functions and match strategies are needed.",
    "step2Title": "Design",
    "step2Text": "Compare ideas and plan the robot structure and mechanisms.",
    "step3Title": "Build",
    "step3Text": "Assemble the frame and components to complete the physical robot.",
    "step4Title": "Programming",
    "step4Text": "Implement sensors, motors, autonomous routines, and driver-control code.",
    "step5Title": "Testing · Competition",
    "step5Text": "Repeat testing and improvement, then operate the robot in actual matches.",
    "competitionKicker": "COMPETITION RECORD",
    "competitionTitle": "Awards &amp; Achievements",
    "competitionText": "2015–2016 Korea Robot Championship, FTC Division — Best Challenge Award<br>2016–2017 Korea Robot Championship, FTC Division — Design Award, 2nd Place Assist<br>2017–2018 Korea Robot Championship, FTC Division — Think Award<br>2018–2019 Korea Robot Championship, FTC Division — Inspire Award (1st Overall), Judge Award<br>2020–2021 Korea Robot Championship, FTC Division — Robot Game Winning 3rd Award (3rd Place)<br>2021–2022 Korea Robot Championship, FTC Division — Inspire Award 2nd Place (2nd Overall), Winning Alliance 1st Place<br>2022–2023 Korea Robot Championship, FTC Division — Creative Award, Judge Award<br>2023 Osan 1st Hackathon — Grand Prize (Jul. 21, 2023 / Osan)<br>2023 KLA Scholarship Program Advance Insights Challenge — Grand Prize (Nov. 20, 2023 / Suwon)<br>2023–2024 Korea Robot Championship, FTC Division — Winning Alliance Captain (1st Place) 23020, Think Award 24906, Winning Alliance 1st Team Selected 24906 (Jan. 27, 2024 / Daejeon)<br>2023–2024 FIRST World Championship — Represented Korea; Judges’ Choice Award 23020 (Apr. 20, 2024 / Houston, USA)<br>2024 Osan 2nd Hackathon — Encouragement Award (Aug. 23, 2024 / Osan)<br>2024 KLA Scholarship Program Advance Insights Challenge — 3rd Place (Nov. 16, 2024 / Suwon)<br>2024–2025 Korea Robot Championship, FTC Division — Inspire Award 1st Place (1st Overall) 23020, Inspire Award 2nd Place (2nd Overall) 24906, Winning Alliance 1st Team Selected 24906, King Sejong Division Winning Alliance 1st Team Selected 24906 (Jan. 20, 2025 / Daejeon)<br>2024–2025 FIRST World Championship — Represented Korea (Apr. 16–19, 2025 / Houston, USA)<br>2025 KLA Scholarship Program — Design Award (24906), Engineering Notes Award (24906)<br>2025–2026 Korea Robot Championship, FTC Division — Inspire Award 3rd Place (3rd Overall) 24906<br>Championship Finalist Alliance Award (24906)<br>2025–2026 FIRST World Championship — Represented Korea (Houston, USA)<br>2026 Mission Master 1st Award, Mission Master 2nd Award (Ulsan)",
    "mediaButton": "See Photos · Videos",
    "mediaKicker": "PHOTOS · VIDEOS",
    "mediaTitle": "See our real activities<br>all in one place.",
    "mediaLead": "This media section is designed for robot photos, build progress, match videos, and code screens.",
    "tabPhotos": "Photos",
    "tabVideos": "Videos",
    "tabCode": "Coding",
    "videoKicker": "VIDEO",
    "videoTitle": "Match Video or<br>Build Timelapse",
    "videoText": "Add an actual MP4 file and it can be played directly here. The title and description can also be edited later.",
    "codeKicker": "ROBOT CODE",
    "codeTitle": "The code that makes<br>our robot move.",
    "codeText": "A short example from the team’s real autonomous, sensor-control, or driver-control code helps visitors understand what students actually work on.",
    "joinKicker": "JOIN TC",
    "joinTitle": "We are looking for teammates<br>to build the next robot with us.",
    "joinLead": "When the recruitment schedule and application method are confirmed, simply replace the fields below with the actual information. The website QR code can be used separately on posters or printed materials instead of being placed inside this page.",
    "recruiting": "RECRUITING",
    "joinHeadline": "If you like robots,<br>or want to build one yourself.",
    "joinText": "An interest in mechanics, programming, or match strategy is enough to begin. Update this section later to match the actual recruitment criteria.",
    "apply": "Open Application Form →",
    "recruitInfo": "Recruitment Information",
    "targetLabel": "Eligibility",
    "targetValue": "Uncheon High School 1st- and 2nd-year students",
    "dateLabel": "Recruitment Period",
    "dateValue": "Recruitment is currently closed.",
    "placeLabel": "Location",
    "placeValue": "[Activity location]",
    "contactLabel": "Contact",
    "contactValue": "[Advisor / contact information]",
    "joinNotice": "Recruitment is currently closed.",
    "footerText": "© 2026 Uncheon High School"
  },
  "ja": {
    "topline": "FTC · ROBOT BUILD · PROGRAMMING",
    "clubName": "TC Robotics Club",
    "schoolName": "雲泉高等学校",
    "navHome": "ホーム",
    "navAbout": "部活紹介",
    "navActivity": "活動・大会",
    "navMedia": "写真・動画",
    "navJoin": "入部案内",
    "heroKicker": "雲泉高等学校 ロボティクス部",
    "heroTitle": "自分たちでロボットを作り、<br><em>自分たちでコードを書き、</em><br>フィールドで動かします。",
    "heroLead": "TCはFTCのようなロボット競技を目標に、機械設計・製作・プログラミング・試合戦略を一緒に経験する部活動です。",
    "heroAbout": "部活を知る",
    "heroJoin": "入部案内",
    "mini1Title": "ROBOT BUILD",
    "mini1Text": "設計・組立・改善",
    "mini2Title": "PROGRAMMING",
    "mini2Text": "センサー・モーター・自律走行",
    "mini3Title": "COMPETITION",
    "mini3Text": "戦略・テスト・試合",
    "mediaHeroLabel": "代表写真または試合動画",
    "seasonLabel": "THIS SEASON",
    "seasonTitle": "1シーズン、1台のロボット。",
    "seasonText": "アイデアから試合まで、チームで完成させます。",
    "strip1Label": "CLUB",
    "strip2Label": "SCHOOL",
    "strip3Label": "TEAM",
    "strip4Label": "FOCUS",
    "strip4Value": "ROBOTICS · FTC",
    "homeKicker": "部活をひと目で",
    "homeTitle": "気になる内容から見てください。",
    "homeCopy": "ホームは要点だけにし、詳しい内容はメニュー別に分けています。写真や活動内容は後から簡単に差し替えられます。",
    "homeCard1Title": "どんな部活ですか？",
    "homeCard1Text": "TCが何を作り、どのように活動しているかを紹介します。",
    "homeCard2Title": "ロボットはどう完成しますか？",
    "homeCard2Text": "競技分析から製作、プログラミング、テストまでの流れを紹介します。",
    "homeCard3Title": "実際の活動を見たい",
    "homeCard3Text": "写真・動画・コードの記録をまとめて掲載できます。",
    "more": "詳しく見る →",
    "aboutKicker": "部活紹介",
    "aboutTitle": "ロボットが好きなら、<br>ここから始められます。",
    "aboutLead": "後で実際の部活紹介、活動目標、雰囲気、大会に参加する理由などを3〜5文程度で入れてください。現在は広報サイトのデザインと構成を先に整えています。",
    "aboutCard1Title": "機械設計・製作",
    "aboutCard1Text": "フレーム、駆動部、競技課題に必要な機構を自分たちで設計・組立します。",
    "aboutCard2Title": "ロボットプログラミング",
    "aboutCard2Text": "モーターやセンサーを制御し、自律走行やドライバー操作のコードを書きます。",
    "aboutCard3Title": "繰り返しテスト",
    "aboutCard3Text": "実際の試合を想定して問題を見つけ、ハードとソフトを改善します。",
    "aboutCard4Title": "チームで解決",
    "aboutCard4Text": "機械、プログラミング、戦略の役割がつながり、1台のロボットを完成させます。",
    "aboutFeatureKicker": "新入部員へ",
    "aboutFeatureTitle": "上手な人より、<br>やってみたい人。",
    "aboutFeatureText": "ロボットやプログラミングが初めてでも大丈夫です。作ること、直すこと、もう一度試すことに興味があれば、活動を通して学べます。",
    "joinButton": "入部案内を見る",
    "activityKicker": "活動・大会",
    "activityTitle": "作って、コードを書いて、<br>試合で確かめます。",
    "activityLead": "実際の参加大会やシーズン日程が決まったら、このページの文章だけ差し替えれば使えます。以下はロボット競技を準備する一般的な流れです。",
    "step1Title": "競技分析",
    "step1Text": "ルールと課題を確認し、必要な機能と試合戦略を決めます。",
    "step2Title": "設計",
    "step2Text": "アイデアを比較し、ロボットの構造と機構を計画します。",
    "step3Title": "製作",
    "step3Text": "フレームや部品を組み立て、実際に動くロボットを作ります。",
    "step4Title": "プログラミング",
    "step4Text": "センサー、モーター、自律走行、操作コードを実装します。",
    "step5Title": "テスト・大会",
    "step5Text": "テストと改善を繰り返し、実際の試合でロボットを運用します。",
    "competitionKicker": "大会記録",
    "competitionTitle": "[参加大会 / シーズン名を入力]",
    "competitionText": "大会名、シーズン目標、準備過程、成果などを実際の情報が整った後に入れてください。",
    "mediaButton": "写真・動画を見る",
    "mediaKicker": "写真・動画",
    "mediaTitle": "実際の活動記録を<br>ひとつの場所に。",
    "mediaLead": "ロボット写真、製作過程、試合動画、コード画面を後から入れられるよう、メディアページを独立させています。",
    "tabPhotos": "写真",
    "tabVideos": "動画",
    "tabCode": "コード",
    "videoKicker": "動画エリア",
    "videoTitle": "試合動画または<br>製作タイムラプス",
    "videoText": "MP4ファイルを追加すると、このエリアで直接再生できます。タイトルや説明も後から変更できます。",
    "codeKicker": "ロボットコード",
    "codeTitle": "ロボットを動かす<br>私たちのコード。",
    "codeText": "自律走行、センサー制御、ドライバー操作など、実際のチームコードの短い例を入れると活動内容が伝わりやすくなります。",
    "joinKicker": "入部案内",
    "joinTitle": "次のロボットを一緒に作る<br>仲間を待っています。",
    "joinLead": "募集日程と応募方法が決まったら、下の項目を実際の情報に差し替えてください。サイトへのQRコードはこのページ内ではなく、ポスターや印刷物で別に使う想定です。",
    "recruiting": "RECRUITING",
    "joinHeadline": "ロボットが好き、<br>または自分で作ってみたいなら。",
    "joinText": "機械、プログラミング、試合戦略のどれかに興味があれば大丈夫です。実際の募集基準に合わせて文章を変更してください。",
    "apply": "応募フォームを接続 →",
    "recruitInfo": "募集情報",
    "targetLabel": "募集対象",
    "targetValue": "[例：雲泉高校 1・2年生]",
    "dateLabel": "募集期間",
    "dateValue": "[募集日程を入力]",
    "placeLabel": "活動場所",
    "placeValue": "[活動場所を入力]",
    "contactLabel": "問い合わせ",
    "contactValue": "[担当者 / 連絡方法]",
    "joinNotice": "応募リンクはGoogleフォーム、Naverフォームなど実際の申請ページに変更できます。",
    "footerText": "© 2026 雲泉高等学校"
  },
  "ru": {
    "topline": "FTC · СБОРКА РОБОТА · ПРОГРАММИРОВАНИЕ",
    "clubName": "TC Robotics Club",
    "schoolName": "Старшая школа Унчхон",
    "navHome": "Главная",
    "navAbout": "О клубе",
    "navActivity": "Деятельность · Соревнования",
    "navMedia": "Фото · Видео",
    "navJoin": "Вступить",
    "heroKicker": "РОБОТОТЕХНИЧЕСКИЙ КЛУБ СТАРШЕЙ ШКОЛЫ УНЧХОН",
    "heroTitle": "Мы сами собираем робота,<br><em>сами пишем код</em><br>и выводим его на поле.",
    "heroLead": "TC — клуб робототехники, где участники проектируют, собирают и программируют роботов, а также разрабатывают стратегию для соревнований, таких как FTC.",
    "heroAbout": "О клубе",
    "heroJoin": "Как вступить",
    "mini1Title": "СБОРКА РОБОТА",
    "mini1Text": "Проектирование · Сборка · Улучшение",
    "mini2Title": "ПРОГРАММИРОВАНИЕ",
    "mini2Text": "Датчики · Моторы · Автономный режим",
    "mini3Title": "СОРЕВНОВАНИЯ",
    "mini3Text": "Стратегия · Тесты · Матч",
    "mediaHeroLabel": "ФОТО КОМАНДЫ ИЛИ ВИДЕО МАТЧА",
    "seasonLabel": "ЭТОТ СЕЗОН",
    "seasonTitle": "Один сезон. Один робот.",
    "seasonText": "От первой идеи до игрового поля — мы создаём его вместе.",
    "strip1Label": "КЛУБ",
    "strip2Label": "ШКОЛА",
    "strip3Label": "КОМАНДА",
    "strip4Label": "НАПРАВЛЕНИЕ",
    "strip4Value": "РОБОТОТЕХНИКА · FTC",
    "homeKicker": "ПОЗНАКОМЬТЕСЬ С КЛУБОМ",
    "homeTitle": "Начните с того, что вам интересно.",
    "homeCopy": "На главной странице собрана только самая важная информация. Подробности находятся в отдельных разделах, а тексты и медиа можно позже заменить на реальные материалы команды.",
    "homeCard1Title": "Что такое TC?",
    "homeCard1Text": "Узнайте, что создаёт команда и как участники работают вместе.",
    "homeCard2Title": "Как создаётся робот?",
    "homeCard2Text": "Проследите весь сезон: от анализа игры и сборки до программирования, тестов и соревнований.",
    "homeCard3Title": "Хотите увидеть настоящую работу?",
    "homeCard3Text": "В разделе медиа можно разместить фотографии, видео и фрагменты кода команды.",
    "more": "Подробнее →",
    "aboutKicker": "О КЛУБЕ",
    "aboutTitle": "Если вам нравятся роботы,<br>начать можно здесь.",
    "aboutLead": "Позже замените этот текст на 3–5 предложений о реальном клубе, его целях, атмосфере и причинах участия в соревнованиях. Макет рекламного сайта уже подготовлен.",
    "aboutCard1Title": "Механика и сборка",
    "aboutCard1Text": "Проектируем и собираем рамы, приводы и механизмы, необходимые для выполнения задач на поле.",
    "aboutCard2Title": "Программирование робота",
    "aboutCard2Text": "Управляем моторами и датчиками, пишем автономные программы и код для управления оператором.",
    "aboutCard3Title": "Тесты и улучшения",
    "aboutCard3Text": "Находим проблемы в условиях, похожих на реальные матчи, и постоянно улучшаем механику и программное обеспечение.",
    "aboutCard4Title": "Решаем задачи командой",
    "aboutCard4Text": "Механика, программирование и стратегия соединяются, чтобы создать одного законченного робота.",
    "aboutFeatureKicker": "НОВЫМ УЧАСТНИКАМ",
    "aboutFeatureTitle": "Необязательно быть экспертом.<br>Главное — хотеть попробовать.",
    "aboutFeatureText": "Ничего страшного, если робототехника или программирование для вас новы. Если вам нравится собирать, исправлять и пробовать снова, вы сможете научиться этому в клубе.",
    "joinButton": "Как вступить",
    "activityKicker": "ДЕЯТЕЛЬНОСТЬ · СОРЕВНОВАНИЯ",
    "activityTitle": "Собираем. Программируем.<br>Проверяем на поле.",
    "activityLead": "Когда будут подтверждены реальные соревнования и расписание сезона, достаточно будет заменить текст на этой странице. Ниже показан типичный процесс подготовки к соревнованиям по робототехнике.",
    "step1Title": "Анализ игры",
    "step1Text": "Изучаем правила и задачу, затем определяем необходимые функции робота и стратегию матча.",
    "step2Title": "Проектирование",
    "step2Text": "Сравниваем идеи и планируем конструкцию и механизмы робота.",
    "step3Title": "Сборка",
    "step3Text": "Собираем раму и компоненты в работающего робота.",
    "step4Title": "Программирование",
    "step4Text": "Настраиваем датчики, моторы, автономные алгоритмы и управление оператором.",
    "step5Title": "Тесты · Соревнования",
    "step5Text": "Повторяем тестирование и улучшения, а затем управляем роботом в настоящих матчах.",
    "competitionKicker": "РЕЗУЛЬТАТЫ СОРЕВНОВАНИЙ",
    "competitionTitle": "[Введите соревнование / сезон]",
    "competitionText": "Когда появятся реальные данные, добавьте сюда название соревнования, цель сезона, процесс подготовки и результаты.",
    "mediaButton": "Фото · Видео",
    "mediaKicker": "ФОТО · ВИДЕО",
    "mediaTitle": "Покажите настоящую работу<br>в одном месте.",
    "mediaLead": "Отдельная медиастраница подготовлена для фотографий робота, процесса сборки, видео матчей и экранов с кодом.",
    "tabPhotos": "Фото",
    "tabVideos": "Видео",
    "tabCode": "Код",
    "videoKicker": "ВИДЕО",
    "videoTitle": "Видео матча или<br>таймлапс сборки",
    "videoText": "Добавьте MP4-файл, и он сможет воспроизводиться прямо здесь. Название и описание также можно изменить позже.",
    "codeKicker": "КОД РОБОТА",
    "codeTitle": "Код, который заставляет<br>нашего робота двигаться.",
    "codeText": "Короткий пример настоящего автономного кода, работы с датчиками или управления поможет посетителям понять, чем занимается клуб.",
    "joinKicker": "ВСТУПИТЬ В TC",
    "joinTitle": "Мы ищем команду,<br>которая построит следующего робота.",
    "joinLead": "Когда будут определены сроки набора и способ подачи заявки, замените поля ниже на реальные данные. QR-код сайта лучше размещать на плакатах и печатных материалах, а не внутри этой страницы.",
    "recruiting": "НАБОР",
    "joinHeadline": "Если вы любите роботов<br>или хотите собрать своего.",
    "joinText": "Для начала достаточно интереса к механике, программированию или стратегии матча. Позже замените этот текст на реальные условия набора.",
    "apply": "Открыть форму заявки →",
    "recruitInfo": "Информация о наборе",
    "targetLabel": "Для кого",
    "targetValue": "[например: 10–11 классы школы Унчхон]",
    "dateLabel": "Период",
    "dateValue": "[Введите даты набора]",
    "placeLabel": "Место",
    "placeValue": "[Введите место занятий]",
    "contactLabel": "Контакты",
    "contactValue": "[Куратор / способ связи]",
    "joinNotice": "Замените ссылку на реальную форму Google Forms, Naver Form или другую страницу подачи заявки.",
    "footerText": "© 2026 Старшая школа Унчхон"
  },
  "hi": {
    "topline": "FTC · रोबोट निर्माण · प्रोग्रामिंग",
    "clubName": "TC Robotics Club",
    "schoolName": "वूनचुन हाई स्कूल",
    "navHome": "मुखपृष्ठ",
    "navAbout": "क्लब परिचय",
    "navActivity": "गतिविधियाँ · प्रतियोगिता",
    "navMedia": "फोटो · वीडियो",
    "navJoin": "जुड़ें",
    "heroKicker": "वूनचुन हाई स्कूल रोबोटिक्स क्लब",
    "heroTitle": "हम खुद रोबोट बनाते हैं,<br><em>खुद कोड लिखते हैं</em><br>और उसे मैदान में उतारते हैं।",
    "heroLead": "TC एक रोबोटिक्स क्लब है जहाँ सदस्य FTC जैसी प्रतियोगिताओं के लिए रोबोट का डिज़ाइन, निर्माण, प्रोग्रामिंग और मैच रणनीति तैयार करते हैं।",
    "heroAbout": "क्लब के बारे में",
    "heroJoin": "कैसे जुड़ें",
    "mini1Title": "रोबोट निर्माण",
    "mini1Text": "डिज़ाइन · निर्माण · सुधार",
    "mini2Title": "प्रोग्रामिंग",
    "mini2Text": "सेंसर · मोटर · स्वायत्त संचालन",
    "mini3Title": "प्रतियोगिता",
    "mini3Text": "रणनीति · परीक्षण · मैच",
    "mediaHeroLabel": "टीम फोटो या मैच वीडियो",
    "seasonLabel": "इस सीज़न",
    "seasonTitle": "एक सीज़न। एक रोबोट।",
    "seasonText": "पहले विचार से मैदान तक, हम इसे मिलकर बनाते हैं।",
    "strip1Label": "क्लब",
    "strip2Label": "स्कूल",
    "strip3Label": "टीम",
    "strip4Label": "मुख्य क्षेत्र",
    "strip4Value": "रोबोटिक्स · FTC",
    "homeKicker": "क्लब को जानें",
    "homeTitle": "अपनी रुचि से शुरू करें।",
    "homeCopy": "मुखपृष्ठ पर केवल मुख्य जानकारी रखी गई है। विस्तृत जानकारी अलग-अलग अनुभागों में है, और बाद में नमूना टेक्स्ट व मीडिया को टीम की वास्तविक सामग्री से आसानी से बदला जा सकता है।",
    "homeCard1Title": "TC किस तरह का क्लब है?",
    "homeCard1Text": "देखें कि टीम क्या बनाती है और सदस्य मिलकर कैसे काम करते हैं।",
    "homeCard2Title": "रोबोट कैसे बनता है?",
    "homeCard2Text": "गेम विश्लेषण से लेकर निर्माण, कोडिंग, परीक्षण और प्रतियोगिता तक पूरे सीज़न की प्रक्रिया देखें।",
    "homeCard3Title": "वास्तविक गतिविधियाँ देखना चाहते हैं?",
    "homeCard3Text": "मीडिया पेज पर टीम की फोटो, वीडियो और कोड दिखाए जा सकते हैं।",
    "more": "विस्तार देखें →",
    "aboutKicker": "क्लब परिचय",
    "aboutTitle": "अगर आपको रोबोट पसंद हैं,<br>तो शुरुआत यहीं से हो सकती है।",
    "aboutLead": "बाद में इस भाग को क्लब के वास्तविक परिचय, लक्ष्य, माहौल और प्रतियोगिताओं में भाग लेने के कारणों पर 3–5 वाक्यों से बदलें। फिलहाल प्रचार साइट का लेआउट तैयार है।",
    "aboutCard1Title": "मैकेनिकल डिज़ाइन और निर्माण",
    "aboutCard1Text": "मैच कार्यों के लिए फ्रेम, ड्राइवट्रेन और आवश्यक तंत्र का डिज़ाइन और निर्माण करते हैं।",
    "aboutCard2Title": "रोबोट प्रोग्रामिंग",
    "aboutCard2Text": "मोटर और सेंसर को नियंत्रित करते हैं तथा स्वायत्त और ड्राइवर-कंट्रोल कोड लिखते हैं।",
    "aboutCard3Title": "परीक्षण और सुधार",
    "aboutCard3Text": "मैच जैसी परिस्थितियों में समस्याएँ खोजकर हार्डवेयर और सॉफ्टवेयर को लगातार बेहतर करते हैं।",
    "aboutCard4Title": "टीम के रूप में समाधान",
    "aboutCard4Text": "मैकेनिकल, प्रोग्रामिंग और रणनीति की भूमिकाएँ मिलकर एक पूरा रोबोट तैयार करती हैं।",
    "aboutFeatureKicker": "नए सदस्यों के लिए",
    "aboutFeatureTitle": "विशेषज्ञ होना ज़रूरी नहीं है।<br>बस कोशिश करने की इच्छा चाहिए।",
    "aboutFeatureText": "यदि रोबोटिक्स या कोडिंग आपके लिए नई है तो भी ठीक है। अगर आपको बनाना, सुधारना और फिर से प्रयास करना पसंद है, तो आप क्लब की गतिविधियों से सीख सकते हैं।",
    "joinButton": "कैसे जुड़ें",
    "activityKicker": "गतिविधियाँ · प्रतियोगिता",
    "activityTitle": "बनाइए। कोड लिखिए।<br>मैदान में साबित कीजिए।",
    "activityLead": "वास्तविक प्रतियोगिता और सीज़न का कार्यक्रम तय होने के बाद इस पेज के टेक्स्ट को बदलना ही पर्याप्त होगा। नीचे रोबोटिक्स प्रतियोगिता की सामान्य तैयारी प्रक्रिया दिखाई गई है।",
    "step1Title": "गेम का विश्लेषण",
    "step1Text": "नियम और चुनौती समझकर आवश्यक कार्यों और मैच रणनीति का निर्णय करते हैं।",
    "step2Title": "डिज़ाइन",
    "step2Text": "विचारों की तुलना कर रोबोट की संरचना और तंत्र की योजना बनाते हैं।",
    "step3Title": "निर्माण",
    "step3Text": "फ्रेम और हिस्सों को जोड़कर एक काम करने वाला रोबोट बनाते हैं।",
    "step4Title": "प्रोग्रामिंग",
    "step4Text": "सेंसर, मोटर, स्वायत्त रूटीन और ड्राइवर नियंत्रण लागू करते हैं।",
    "step5Title": "परीक्षण · प्रतियोगिता",
    "step5Text": "बार-बार परीक्षण और सुधार के बाद वास्तविक मैच में रोबोट चलाते हैं।",
    "competitionKicker": "प्रतियोगिता रिकॉर्ड",
    "competitionTitle": "[प्रतियोगिता / सीज़न का नाम लिखें]",
    "competitionText": "वास्तविक जानकारी मिलने पर प्रतियोगिता का नाम, सीज़न लक्ष्य, तैयारी प्रक्रिया और परिणाम यहाँ जोड़ें।",
    "mediaButton": "फोटो · वीडियो देखें",
    "mediaKicker": "फोटो · वीडियो",
    "mediaTitle": "अपना वास्तविक काम<br>एक ही जगह दिखाएँ।",
    "mediaLead": "यह अलग मीडिया पेज रोबोट की फोटो, निर्माण प्रक्रिया, मैच वीडियो और कोड स्क्रीन दिखाने के लिए तैयार है।",
    "tabPhotos": "फोटो",
    "tabVideos": "वीडियो",
    "tabCode": "कोड",
    "videoKicker": "वीडियो क्षेत्र",
    "videoTitle": "मैच वीडियो या<br>निर्माण टाइमलैप्स",
    "videoText": "MP4 फ़ाइल जोड़ने पर वीडियो यहीं चल सकता है। शीर्षक और विवरण बाद में भी बदले जा सकते हैं।",
    "codeKicker": "रोबोट कोड",
    "codeTitle": "वह कोड जो<br>हमारे रोबोट को चलाता है।",
    "codeText": "वास्तविक स्वायत्त, सेंसर या ड्राइवर-कंट्रोल कोड का छोटा उदाहरण लोगों को क्लब की गतिविधियाँ समझने में मदद करता है।",
    "joinKicker": "TC से जुड़ें",
    "joinTitle": "हम उन साथियों की तलाश में हैं<br>जो अगला रोबोट बनाएँगे।",
    "joinLead": "भर्ती की तारीखें और आवेदन विधि तय होने पर नीचे की जानकारी को वास्तविक विवरण से बदलें। वेबसाइट का QR कोड इस पेज के बजाय पोस्टर या प्रिंट सामग्री पर रखें।",
    "recruiting": "भर्ती",
    "joinHeadline": "अगर आपको रोबोट पसंद हैं<br>या खुद बनाना चाहते हैं।",
    "joinText": "शुरुआत के लिए मैकेनिक्स, प्रोग्रामिंग या मैच रणनीति में रुचि ही पर्याप्त है। बाद में इसे वास्तविक भर्ती मानदंड से बदलें।",
    "apply": "आवेदन फ़ॉर्म खोलें →",
    "recruitInfo": "भर्ती जानकारी",
    "targetLabel": "किसके लिए",
    "targetValue": "[उदा. वूनचुन हाई स्कूल कक्षा 10–11]",
    "dateLabel": "अवधि",
    "dateValue": "[भर्ती की तारीखें लिखें]",
    "placeLabel": "स्थान",
    "placeValue": "[गतिविधि स्थान लिखें]",
    "contactLabel": "संपर्क",
    "contactValue": "[सलाहकार / संपर्क माध्यम]",
    "joinNotice": "आवेदन लिंक को वास्तविक Google Forms, Naver Form या अन्य आवेदन पेज से बदलें।",
    "footerText": "© 2026 वूनचुन हाई स्कूल"
  },
  "bg": {
    "topline": "FTC · ИЗГРАЖДАНЕ НА РОБОТ · ПРОГРАМИРАНЕ",
    "clubName": "TC Robotics Club",
    "schoolName": "Гимназия Унчхон",
    "navHome": "Начало",
    "navAbout": "За клуба",
    "navActivity": "Дейности · Състезания",
    "navMedia": "Снимки · Видео",
    "navJoin": "Присъедини се",
    "heroKicker": "КЛУБ ПО РОБОТИКА НА ГИМНАЗИЯ УНЧХОН",
    "heroTitle": "Ние сами строим робота,<br><em>сами пишем кода</em><br>и го извеждаме на терена.",
    "heroLead": "TC е клуб по роботика, в който учениците проектират, изграждат и програмират роботи и разработват състезателна стратегия за турнири като FTC.",
    "heroAbout": "За клуба",
    "heroJoin": "Как да се включиш",
    "mini1Title": "ИЗГРАЖДАНЕ НА РОБОТ",
    "mini1Text": "Дизайн · Изграждане · Подобряване",
    "mini2Title": "ПРОГРАМИРАНЕ",
    "mini2Text": "Сензори · Мотори · Автономен режим",
    "mini3Title": "СЪСТЕЗАНИЯ",
    "mini3Text": "Стратегия · Тест · Мач",
    "mediaHeroLabel": "СНИМКА НА ОТБОРА ИЛИ ВИДЕО ОТ МАЧ",
    "seasonLabel": "ТОЗИ СЕЗОН",
    "seasonTitle": "Един сезон. Един робот.",
    "seasonText": "От първата идея до терена го изграждаме заедно.",
    "strip1Label": "КЛУБ",
    "strip2Label": "УЧИЛИЩЕ",
    "strip3Label": "ОТБОР",
    "strip4Label": "ФОКУС",
    "strip4Value": "РОБОТИКА · FTC",
    "homeKicker": "РАЗГЛЕДАЙ КЛУБА",
    "homeTitle": "Започни от това, което те интересува.",
    "homeCopy": "Началната страница показва само най-важното. Отвори отделните секции за подробности и по-късно замени примерните текстове и медии с реално съдържание на отбора.",
    "homeCard1Title": "Какъв клуб е TC?",
    "homeCard1Text": "Виж какво създава отборът и как членовете работят заедно.",
    "homeCard2Title": "Как се изгражда един робот?",
    "homeCard2Text": "Проследи целия сезон — от анализ на играта до изграждане, програмиране, тестове и състезание.",
    "homeCard3Title": "Искаш да видиш реални дейности?",
    "homeCard3Text": "В медийната страница могат да се покажат снимки, видео и код от отбора.",
    "more": "Виж подробности →",
    "aboutKicker": "ЗА КЛУБА",
    "aboutTitle": "Ако харесваш роботи,<br>можеш да започнеш оттук.",
    "aboutLead": "По-късно замени този текст с 3–5 изречения за истинския клуб, целите му, атмосферата и причините да участва в състезания. Засега рекламното оформление е готово.",
    "aboutCard1Title": "Механичен дизайн и изграждане",
    "aboutCard1Text": "Проектираме и сглобяваме рамки, задвижвания и механизми, нужни за задачите в мача.",
    "aboutCard2Title": "Програмиране на робот",
    "aboutCard2Text": "Управляваме мотори и сензори и пишем автономен код и код за управление от оператор.",
    "aboutCard3Title": "Тест и подобрение",
    "aboutCard3Text": "Откриваме проблеми в условия, близки до реален мач, и постоянно подобряваме хардуера и софтуера.",
    "aboutCard4Title": "Решаваме като отбор",
    "aboutCard4Text": "Механика, програмиране и стратегия се свързват, за да завършим един робот.",
    "aboutFeatureKicker": "ЗА НОВИ ЧЛЕНОВЕ",
    "aboutFeatureTitle": "Не е нужно да си експерт.<br>Трябва само да искаш да опиташ.",
    "aboutFeatureText": "Няма проблем, ако роботиката или програмирането са нови за теб. Ако обичаш да създаваш, поправяш и опитваш отново, можеш да се учиш чрез клуба.",
    "joinButton": "Виж как да се включиш",
    "activityKicker": "ДЕЙНОСТИ · СЪСТЕЗАНИЯ",
    "activityTitle": "Изгради го. Програмирай го.<br>Докажи го на терена.",
    "activityLead": "След като бъдат потвърдени реалните състезания и графикът на сезона, ще е достатъчно да смениш текста на тази страница. Долу е показан типичен процес за подготовка за състезание по роботика.",
    "step1Title": "Анализ на играта",
    "step1Text": "Изучаваме правилата и предизвикателството, после определяме нужните функции и стратегия за мача.",
    "step2Title": "Дизайн",
    "step2Text": "Сравняваме идеи и планираме структурата и механизмите на робота.",
    "step3Title": "Изграждане",
    "step3Text": "Сглобяваме рамката и компонентите в работещ робот.",
    "step4Title": "Програмиране",
    "step4Text": "Реализираме сензори, мотори, автономни алгоритми и управление от оператор.",
    "step5Title": "Тест · Състезание",
    "step5Text": "Повтаряме тестовете и подобренията, след което управляваме робота в реални мачове.",
    "competitionKicker": "РЕЗУЛТАТИ ОТ СЪСТЕЗАНИЯ",
    "competitionTitle": "[Въведи състезание / сезон]",
    "competitionText": "Когато има реална информация, добави тук името на състезанието, целта за сезона, подготовката и резултатите.",
    "mediaButton": "Виж снимки · видео",
    "mediaKicker": "СНИМКИ · ВИДЕО",
    "mediaTitle": "Покажи реалната си работа<br>на едно място.",
    "mediaLead": "Тази отделна медийна страница е готова за снимки на робота, процеса на изграждане, видео от мачове и екрани с код.",
    "tabPhotos": "Снимки",
    "tabVideos": "Видео",
    "tabCode": "Код",
    "videoKicker": "ВИДЕО",
    "videoTitle": "Видео от мач или<br>таймлапс на изграждането",
    "videoText": "Добави MP4 файл и той може да се възпроизвежда директно тук. Заглавието и описанието могат да се променят по-късно.",
    "codeKicker": "КОД НА РОБОТА",
    "codeTitle": "Кодът, който кара<br>нашия робот да се движи.",
    "codeText": "Кратък пример от реален автономен код, работа със сензори или управление помага на посетителите да разберат какво прави клубът.",
    "joinKicker": "ПРИСЪЕДИНИ СЕ КЪМ TC",
    "joinTitle": "Търсим отбора,<br>който ще изгради следващия робот.",
    "joinLead": "Когато бъдат определени датите за прием и начинът за кандидатстване, замени полетата долу с реалната информация. QR кодът на сайта е по-добре да бъде на плакати и печатни материали, а не вътре в тази страница.",
    "recruiting": "ПРИЕМ",
    "joinHeadline": "Ако харесваш роботи<br>или искаш сам да построиш такъв.",
    "joinText": "Интерес към механика, програмиране или стратегия за мач е достатъчен за начало. По-късно замени текста с реалните критерии за прием.",
    "apply": "Отвори формуляра →",
    "recruitInfo": "Информация за прием",
    "targetLabel": "За кого",
    "targetValue": "[напр. 10–11 клас в гимназия Унчхон]",
    "dateLabel": "Период",
    "dateValue": "[Въведи датите за прием]",
    "placeLabel": "Място",
    "placeValue": "[Въведи мястото за дейности]",
    "contactLabel": "Контакт",
    "contactValue": "[Ръководител / начин за връзка]",
    "joinNotice": "Замени адреса за кандидатстване с реална Google Forms, Naver Form или друга страница за записване.",
    "footerText": "© 2026 Гимназия Унчхон"
  }
};
